SET NAMES utf8;
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `TEST_GENERATORE_CARICATO`;

CREATE TABLE `TEST_GENERATORE_CARICATO` (
  `ID` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `VERSION` int NOT NULL,
  `STATO` enum('READY','SCHEDULED','PAUSED','RUNNING','COMPLETED') NOT NULL,
  `ID_GRUPPO` int NOT NULL,
  `MODIFIED_WHEN` datetime NOT NULL,
  `CREATED_WHEN` datetime NOT NULL,
  `ID_LINEA_CHIAMANTE` int NOT NULL,
  `ID_LINEA_CHIAMATO` int NOT NULL,
  `ID_OBP_CHIAMANTE` int NOT NULL,
  `ID_OBP_CHIAMATO` int NOT NULL,
  `NOME` varchar(80) NOT NULL,
  `CREATED_BY` varchar(25) NOT NULL,
  `MODIFIED_BY` varchar(25) NOT NULL,
  `RATE` bigint NOT NULL,
  `DURATA_TRAFFICO` bigint NOT NULL,
  `SCHEDULE_DATETIME` datetime NULL,
  `SCHEDULE_DELAY` bigint NULL,
  `DESCRIZIONE` varchar(1000) NULL,
  `ID_TEMPLATE` int NULL,
  `ID_TEST_GENERATORE` bigint NULL,
  `START_DATE` datetime NULL,
  `END_DATE` datetime NULL,
  FOREIGN KEY (`ID_GRUPPO`) REFERENCES `GRUPPO` (`ID_GRUPPO`),
  FOREIGN KEY (`ID_LINEA_CHIAMANTE`) REFERENCES `LINEE_GEN` (`ID_LINEA_GEN`),
  FOREIGN KEY (`ID_LINEA_CHIAMATO`) REFERENCES `LINEE_GEN` (`ID_LINEA_GEN`),
  FOREIGN KEY (`ID_OBP_CHIAMANTE`) REFERENCES `OUTBOUNDPROXY` (`ID_OBP`),
  FOREIGN KEY (`ID_OBP_CHIAMATO`) REFERENCES `OUTBOUNDPROXY` (`ID_OBP`),
  FOREIGN KEY (`ID_TEMPLATE`) REFERENCES `TEMPLATE` (`ID_TEMPLATE`) ON DELETE SET NULL,
  FOREIGN KEY (`ID_TEST_GENERATORE`) REFERENCES `TEST_GENERATORE` (`ID`) ON DELETE SET NULL
) ENGINE='InnoDB' COLLATE 'utf8mb4_general_ci';

