SET NAMES utf8;
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `TIPO_TEMPLATE`;

CREATE TABLE `TIPO_TEMPLATE` (
  `NOME` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `TIPO_TEMPLATE` (`NOME`) VALUES
('3PY'),
('CFB'),
('CFU – CFNR – CW – CFnoAv'),
('Chiamata Base'),
('Chiamate ACU – CDC –NNG'),
('Manovra'),
('Registrazione/Deregistrazione');

INSERT INTO `TIPO_TEMPLATE`
SELECT DISTINCT TYPE_TEMPLATE FROM TEMPLATE WHERE TYPE_TEMPLATE NOT IN (SELECT NOME FROM TIPO_TEMPLATE)
;

ALTER TABLE `TEMPLATE`
CHANGE `TYPE_TEMPLATE` `TYPE_TEMPLATE` varchar(40) COLLATE 'utf8mb4_general_ci' NULL AFTER `DURATA`,
ADD FOREIGN KEY (`TYPE_TEMPLATE`) REFERENCES `TIPO_TEMPLATE` (`NOME`);

ALTER TABLE `TYPE_LINEE`
ADD `NATURA` enum('REALE','SIMULATO') NOT NULL DEFAULT 'REALE' AFTER `CREATED_BY`;
