
INSERT INTO `FUNZIONE` (`CODICE`, `NOME`, `DESCRIZIONE`) VALUES
('group.delete',	'Elimina gruppo',	'Rimuove un gruppo dal sistema'),
('group.edit',	'Modifica gruppo',	'Consente di modificare un gruppo'),
('group.view',	'Mostra gruppi',	'Consente di accedere ai gruppi di utente'),
('level.delete',	'Elimina livello',	'Consente di eliminare un livello'),
('level.edit',	'Modifica livello',	'Consente di modificare un livello'),
('level.view',	'Mostra i livelli',	'Consente di accedere ai livelli definiti nel sistema'),
('linea.delete',	'Elimina linea',	'Consente di eliminare una linea'),
('linea.edit',	'Modifica linea',	'consente di modificare una linea'),
('linea.view',	'Mostra le linee',	'Consente di accedere alle linee presenti nel sistema'),
('obp.delete',	'Elimina Outbound Proxy',	'Consente di eliminare un Outbound Proxy'),
('obp.edit',	'Modifica Outbound Proxy',	'Consente di creare o modificare un Outbound Proxy'),
('obp.view',	'Mostra gli Outbound Proxy',	'Consente di accedere agli Outbound Proxy definiti nel sistema'),
('user.delete',	'Elimina utente',	'Consente di rimuovere un utente dal sistema'),
('user.edit',	'Modifica utente',	'Consente di aggiungere o modificare gli utenti che possono accedere al sistema'),
('user.view',	'Accedi dati utente',	'Consente di accedere ai dati di un altro utente'),
('template.view', 'Mostra test template', 'Consente di visualizzare i test template definiti nel sistema'),
('template.edit', 'Modifica Test Template', 'Consente di modificare un template per la creazione dei test case'),
('template.delete', 'Elimina test Template', 'Consente di eliminare i template dei test definiti nel sistema');

INSERT INTO `LEVEL` (`ID_LEVEL`, `DESCRIZIONE`, `LEVEL`) VALUES
(2,	'Descrizione livello admin',	'ADMIN'),
(4,	'Regional',	'Lead Operations Manager'),
(6,	'Descrizione Level 5',	'Level 6');

INSERT INTO `GRUPPO` (`ID_GRUPPO`, `DESCRIZIONE`, `GRUPPO`) VALUES
(1,	'g1',	'g1'),
(2,	'Forward',	'Central Integration Designer');

INSERT INTO `UTENZE` (`ID_UTENZA`, `USERNAME`, `PASSWORD`, `ID_LEVEL`, `ID_GROUP`, `NOME`, `COGNOME`, `AZIENDA`, `EMAIL`) VALUES
(1, 'test',	'{noop}test',	2,	1,	'nome',	'cognome',	'azienda',	'test@test.it');

INSERT INTO AUTORIZZAZIONE_LEVEL(ID_LEVEL, FUNZIONE_CODICE)
SELECT L.ID_LEVEL, F.CODICE
FROM (LEVEL L, FUNZIONE F)
LEFT JOIN AUTORIZZAZIONE_LEVEL AL ON (AL.ID_LEVEL = L.ID_LEVEL AND AL.FUNZIONE_CODICE=F.CODICE)
WHERE LEVEL = 'ADMIN'
AND AL.ID_LEVEL IS NULL
;

INSERT INTO `TYPE_LINEE` (`ID_TYPE_LINEA`, `DESCRIZIONE`) VALUES
(1,	'descrizione type linea 1'),
(2,	'descrizione type linea 2');

INSERT INTO `LINEE` (`ID_LINEA`, `NUMERO`, `ID_TYPE_LINEA`, `IP_LINEA`, `PORTA`, `PASSWORD`) VALUES
(1,	'90-400-754-1037',	1,	'240.195.169.235',	924,	'IdZtVacO4inAlAw'),
(2,	'9042382',	1,	'241.88.251.202',	224,	'passwordSegreta');


-- 2021-08-09 Solo per prepopolare alcuni file per lo sviluppo sui template

INSERT INTO `TEMPLATE` (`ID_TEMPLATE`, `VERSION`, `NOME`, `DURATA`, `TYPE_TEMPLATE`, `MODIFIED_BY`, `MODIFIED_WHEN`, `CREATED_BY`, `CREATED_WHEN`, `DESCRIZIONE`) VALUES
(1,	21,	'Template 1',	57,	'bohh',	'test',	'2021-08-09 20:01:13',	'test',	'2021-08-06 18:41:30',	'Descrizione molto lunga per il template 1');

INSERT INTO `FILE_SYSTEM` (`ID`, `VERSION`, `SCOPE`, `ID_REF`, `PATH`, `MODIFIED_BY`, `CREATED_BY`, `MODIFIED_WHEN`, `CREATED_WHEN`, `CONTENT`) VALUES
(1,	0,	'TEMPLATE',	1,	'file1.xml',	'roby',	'roby',	'2021-08-09 11:03:10',	'2021-08-09 11:03:10',	'<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n	xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n	<modelVersion>4.0.0</modelVersion>\n	<parent>\n		<groupId>org.springframework.boot</groupId>\n		<artifactId>spring-boot-starter-parent</artifactId>\n		<version>2.5.0</version>\n		<relativePath/> <!-- lookup parent from repository -->\n	</parent>\n	<groupId>it.reply.sipp</groupId>\n	<artifactId>sipp</artifactId>\n	<version>0.0.1-SNAPSHOT</version>\n	<packaging>war</packaging>\n	<name>sipp</name>\n	<description>Sipp project</description>\n	<properties>\n		<java.version>11</java.version>\n	</properties>\n	<dependencies>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jdbc</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jpa</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-security</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-web</artifactId>\n		</dependency>\n\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-devtools</artifactId>\n			<scope>runtime</scope>\n			<optional>true</optional>\n		</dependency>\n		<dependency>\n			<groupId>mysql</groupId>\n			<artifactId>mysql-connector-java</artifactId>\n			<scope>runtime</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-tomcat</artifactId>\n			<scope>provided</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.security</groupId>\n			<artifactId>spring-security-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>com.auth0</groupId>\n			<artifactId>java-jwt</artifactId>\n			<version>3.16.0</version>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-validation</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.apache.commons</groupId>\n			<artifactId>commons-lang3</artifactId>\n		</dependency>\n	</dependencies>\n\n	<build>\n		<plugins>\n			<plugin>\n				<groupId>org.springframework.boot</groupId>\n				<artifactId>spring-boot-maven-plugin</artifactId>\n			</plugin>\n		</plugins>\n	</build>\n\n</project>\n'),
(2,	0,	'TEMPLATE',	1,	'file2.xml',	'roby',	'roby',	'2021-08-09 11:03:10',	'2021-08-09 11:03:10',	'<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n	xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n	<modelVersion>4.0.0</modelVersion>\n	<parent>\n		<groupId>org.springframework.boot</groupId>\n		<artifactId>spring-boot-starter-parent</artifactId>\n		<version>2.5.0</version>\n		<relativePath/> <!-- lookup parent from repository -->\n	</parent>\n	<groupId>it.reply.sipp</groupId>\n	<artifactId>sipp</artifactId>\n	<version>0.0.1-SNAPSHOT</version>\n	<packaging>war</packaging>\n	<name>sipp</name>\n	<description>Sipp project</description>\n	<properties>\n		<java.version>11</java.version>\n	</properties>\n	<dependencies>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jdbc</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jpa</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-security</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-web</artifactId>\n		</dependency>\n\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-devtools</artifactId>\n			<scope>runtime</scope>\n			<optional>true</optional>\n		</dependency>\n		<dependency>\n			<groupId>mysql</groupId>\n			<artifactId>mysql-connector-java</artifactId>\n			<scope>runtime</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-tomcat</artifactId>\n			<scope>provided</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.security</groupId>\n			<artifactId>spring-security-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>com.auth0</groupId>\n			<artifactId>java-jwt</artifactId>\n			<version>3.16.0</version>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-validation</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.apache.commons</groupId>\n			<artifactId>commons-lang3</artifactId>\n		</dependency>\n	</dependencies>\n\n	<build>\n		<plugins>\n			<plugin>\n				<groupId>org.springframework.boot</groupId>\n				<artifactId>spring-boot-maven-plugin</artifactId>\n			</plugin>\n		</plugins>\n	</build>\n\n</project>\n'),
(3,	0,	'TEMPLATE',	1,	'file3.xml',	'roby',	'roby',	'2021-08-09 11:03:10',	'2021-08-09 11:03:10',	'<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n	xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n	<modelVersion>4.0.0</modelVersion>\n	<parent>\n		<groupId>org.springframework.boot</groupId>\n		<artifactId>spring-boot-starter-parent</artifactId>\n		<version>2.5.0</version>\n		<relativePath/> <!-- lookup parent from repository -->\n	</parent>\n	<groupId>it.reply.sipp</groupId>\n	<artifactId>sipp</artifactId>\n	<version>0.0.1-SNAPSHOT</version>\n	<packaging>war</packaging>\n	<name>sipp</name>\n	<description>Sipp project</description>\n	<properties>\n		<java.version>11</java.version>\n	</properties>\n	<dependencies>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jdbc</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jpa</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-security</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-web</artifactId>\n		</dependency>\n\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-devtools</artifactId>\n			<scope>runtime</scope>\n			<optional>true</optional>\n		</dependency>\n		<dependency>\n			<groupId>mysql</groupId>\n			<artifactId>mysql-connector-java</artifactId>\n			<scope>runtime</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-tomcat</artifactId>\n			<scope>provided</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.security</groupId>\n			<artifactId>spring-security-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>com.auth0</groupId>\n			<artifactId>java-jwt</artifactId>\n			<version>3.16.0</version>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-validation</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.apache.commons</groupId>\n			<artifactId>commons-lang3</artifactId>\n		</dependency>\n	</dependencies>\n\n	<build>\n		<plugins>\n			<plugin>\n				<groupId>org.springframework.boot</groupId>\n				<artifactId>spring-boot-maven-plugin</artifactId>\n			</plugin>\n		</plugins>\n	</build>\n\n</project>\n'),
(4,	0,	'TEMPLATE',	1,	'file4.xml',	'roby',	'roby',	'2021-08-09 11:03:10',	'2021-08-09 11:03:10',	'<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n	xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">\n	<modelVersion>4.0.0</modelVersion>\n	<parent>\n		<groupId>org.springframework.boot</groupId>\n		<artifactId>spring-boot-starter-parent</artifactId>\n		<version>2.5.0</version>\n		<relativePath/> <!-- lookup parent from repository -->\n	</parent>\n	<groupId>it.reply.sipp</groupId>\n	<artifactId>sipp</artifactId>\n	<version>0.0.1-SNAPSHOT</version>\n	<packaging>war</packaging>\n	<name>sipp</name>\n	<description>Sipp project</description>\n	<properties>\n		<java.version>11</java.version>\n	</properties>\n	<dependencies>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jdbc</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-data-jpa</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-security</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-web</artifactId>\n		</dependency>\n\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-devtools</artifactId>\n			<scope>runtime</scope>\n			<optional>true</optional>\n		</dependency>\n		<dependency>\n			<groupId>mysql</groupId>\n			<artifactId>mysql-connector-java</artifactId>\n			<scope>runtime</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-tomcat</artifactId>\n			<scope>provided</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.security</groupId>\n			<artifactId>spring-security-test</artifactId>\n			<scope>test</scope>\n		</dependency>\n		<dependency>\n			<groupId>com.auth0</groupId>\n			<artifactId>java-jwt</artifactId>\n			<version>3.16.0</version>\n		</dependency>\n		<dependency>\n			<groupId>org.springframework.boot</groupId>\n			<artifactId>spring-boot-starter-validation</artifactId>\n		</dependency>\n		<dependency>\n			<groupId>org.apache.commons</groupId>\n			<artifactId>commons-lang3</artifactId>\n		</dependency>\n	</dependencies>\n\n	<build>\n		<plugins>\n			<plugin>\n				<groupId>org.springframework.boot</groupId>\n				<artifactId>spring-boot-maven-plugin</artifactId>\n			</plugin>\n		</plugins>\n	</build>\n\n</project>\n');

INSERT INTO `TEMPLATE_FILE` (`ID`, `TEMPLATE_ID`, `FILE_SYSTEM_ID`, `CATEGORY`, `ORDERING`) VALUES
(4,	1,	1,	'CHIAMATO',	1),
(6,	1,	2,	'CHIAMANTE',	3),
(5,	1,	3,	'CHIAMANTE',	2),
(1,	1,	4,	'CHIAMANTE',	1);
